### ISSUE TITLE
Errors during initial setup

### ISSUE THREAD

**Issue by nasedil** [AlesTsurko/cells#1]
When I try to install dependencies using poetry with command `poetry install` I get the following output:
```
(base) /cells$ $HOME/.poetry/bin/poetry install
Installing dependencies from lock file
                                  
[NonExistentKey]   
'Key "hashes" does not exist.'  
                                  
install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]

(base) /cells$ $HOME/.poetry/bin/poetry -v install
Using virtualenv: ~/.cache/pypoetry/virtualenvs/cells-py3.7
                                   
[MissingArguments]  
Not enough arguments             
                                   
Exception trace:
 ~/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 ~/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 ~/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 ~/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 ~/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/base_command.py in run() at line 141
   input_.validate()
 ~/.poetry/lib/poetry/_vendor/py3.7/cleo/inputs/input.py in validate() at line 68
   raise MissingArguments('Not enough arguments')

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

I've discovered similar issue in https://github.com/sdispater/poetry/issues/1510 but not sure if they are related.

**Comment by nasedil** [comment]
I've tried the newest pre-release version 1.0.0b4 of poetry, it worked.  I suppose it should be working with regular versions when https://github.com/sdispater/poetry/issues/1510 is fixed.

**Comment by nasedil** [comment]
There is another bug in poetry which affects the program:  https://github.com/sdispater/poetry/issues/1503

After running `poetry shell`, typed characters are not echoed, so you cannot see what you type.

**Comment by nasedil** [comment]
Besides that, when typing `python cells -d` in poetry shell for the first time, the program complains about non-existing settings file:
```
(.venv) genio@ep-workstation-main:~/gart/prog/_contrib/cells$ QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Traceback (most recent call last):
  File "~/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "~/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "cells/__main__.py", line 14, in <module>
    main()
  File "cells/__main__.py", line 8, in main
    app = App(subject)
  File "~/gart/prog/_contrib/cells/cells/view/app.py", line 33, in __init__
    self.main = Main(subject)
  File "~/gart/prog/_contrib/cells/cells/view/main.py", line 22, in __init__
    self.settings = SettingsModel(self.subject)
  File "~/gart/prog/_contrib/cells/cells/settings.py", line 36, in __init__
    self.open()
  File "~/gart/prog/_contrib/cells/cells/settings.py", line 64, in open
    with open(self.path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/.config/Cells/settings.toml'
```
After running `touch ~/.config/Cells/settings.toml` I managed to make it running.

**Comment by AlesTsurko** [comment]
For this:
> There is another bug in poetry which affects the program: sdispater/poetry#1503
>
> After running poetry shell, typed characters are not echoed, so you cannot see what you type.

Try:

```
poetry run cells -- -d
```
Without `poetry shell`.

I think the last one should be separated into another issue.

Thank you again!

**Comment by AlesTsurko** [comment]
I fixed the issue related to `FileNotFoundError`.

Let me know if `poetry run cells -- -d` works for you.

**Comment by nasedil** [comment]
@AlesTsurko `poetry run cells -- -d` results with `cells: error: unrecognized arguments: -- -d`, but `poetry run cells -d` works.
